### ISSUE TITLE
Linux client.FinancesAPI.ListFinancialEventGroups

### ISSUE THREAD

**Issue by mbolder** [fond-of-vertigo/amazon-sp-api#42]
We are developing our code on Macs and have no problems with your brilliant api, but moving to a Linux server environment, we are stuck. The exact same code produces a valid response on a Mac, but only an empty response in Linux. 

e.g. client.FinancesAPI.ListFinancialEventGroups results in : &{200 0x14000e34520 <nil>}
but with linux we receive : &{200 <nil> <nil>}

On which os is the api developed ? Are we missing something ? 

PS: Looking deeper into the error, it seems the rdt-token is requested but returns no error or valid token, instead just a nil value is passed back ......

**Comment by Coffeeri** [comment]
We are using the api on both Macs and linux servers in production. That the library behaves differently on your two systems seems odd at first glance. Are both using the same version and configuration parameters?

Moreover I am confused that you are using restricted data tokens, as ListFinancialEventGroups is not on the list for PII, see: 
https://developer-docs.amazon.com/sp-api/changelog/update-discontinued-support-lwa-tokens-can-no-longer-retrieve-pii-in-selling-partner-api

**Comment by Coffeeri** [comment]
> PS: Looking deeper into the error, it seems the rdt-token is requested but returns no error or valid token, instead just a nil value is passed back ......

If I understand you correctly, this may be fixed by 72d584d.

**Comment by mbolder** [comment]
Thank you very much for your fast response. Upon your question I double checked my mod file. Turns out we had been using v. 0.6.3 on our Macs and pulled 0.6.5 when we installed on linux. I changed the token_updater line 68, but I am not sure if that fixed it. For now we will just pull 0.6.3 on linux as well.

**Comment by Coffeeri** [comment]
I think I have solved your issue in #46, amazon used to provide the content-length header. As it stopped doing that, the rdt-call would not unmarshal the response body.

**Comment by Coffeeri** [comment]
I will release this and other additions in the next couple minutes @mbolder.

**Comment by mbolder** [comment]
Brilliant and thank you again for the only useable SP-API on go.

**Comment by Coffeeri** [comment]
I've published v0.7.0, please check if everything works as expected when you have time.

**Comment by mbolder** [comment]
Works on my end.
